### ISSUE TITLE
Create updated Grafana dashboard(s) to be used by Winter 2023 tests and operations.

### ISSUE THREAD

**Issue by philipdoucla** [UCLA-Rocket-Project/AresSoftware#34]
Sister ticket to #9, but instead for Winter 2023 operations.

Must support:
- PT and LC calibrations (date TBD)
- Cold Flow, 1/29
- Hot Fire, 2/3-2/4

**Comment by harrisonCassar** [comment]
https://github.com/UCLA-Rocket-Project/AresSoftware/issues/9#issuecomment-1294639734

Due to all requirements met, our team + Propulsion decided to move forward with using the existing "Draft" dashboard as our main Dashboard for operation.

Although we aim to develop a more specific set of dashboards in the future (covered with #50), this ticket aimed to capture a specific set meant for the Winter 2023 operations, which has now been completed. We therefore close this issue.
